//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primer
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T статус обращения.
    /// </summary>
    //  *** Start programmer edit section *** (tСтатусОбращения CustomAttributes)

    //  *** End programmer edit section *** (tСтатусОбращения CustomAttributes)
    public enum tСтатусОбращения
    {
        
        //  *** Start programmer edit section *** (tСтатусОбращения.Открыто CustomAttributes)

        //  *** End programmer edit section *** (tСтатусОбращения.Открыто CustomAttributes)
        Открыто,
        
        //  *** Start programmer edit section *** (tСтатусОбращения.НаКонтроле CustomAttributes)

        //  *** End programmer edit section *** (tСтатусОбращения.НаКонтроле CustomAttributes)
        НаКонтроле,
        
        //  *** Start programmer edit section *** (tСтатусОбращения.ПрисоединеноКЗаявке CustomAttributes)

        //  *** End programmer edit section *** (tСтатусОбращения.ПрисоединеноКЗаявке CustomAttributes)
        ПрисоединеноКЗаявке,
        
        //  *** Start programmer edit section *** (tСтатусОбращения.Закрыто CustomAttributes)

        //  *** End programmer edit section *** (tСтатусОбращения.Закрыто CustomAttributes)
        Закрыто,
    }
}
