//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primer
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращение.
    /// </summary>
    //  *** Start programmer edit section *** (Обращение CustomAttributes)

    //  *** End programmer edit section *** (Обращение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбращениеE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Обратившийся as \'ФИО обратившегося\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "Причина",
            "ДопОбращение",
            "Ответственный as \'Ответственный\'",
            "ТипОбращения as \'Тип обращения\'",
            "ВидОбращения as \'Вид обращения\'",
            "Оператор as \'Оператор\'"})]
    [MasterViewDefineAttribute("ОбращениеE", "Причина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "ДопОбращение", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ОбращениеE", "Ответственный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбращениеE", "ТипОбращения", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "ВидОбращения", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОбращениеL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "ДопОбращение.Номер as \'Дополнительное обращение\'",
            "Обратившийся as \'ФИО обратившегося\'",
            "Причина.Название as \'Причина\'",
            "Ответственный as \'Ответственный\'",
            "ТипОбращения as \'Название\'",
            "ВидОбращения as \'Название\'",
            "Оператор as \'Оператор\'"}, Hidden=new string[] {
            "Ответственный",
            "ТипОбращения",
            "ВидОбращения",
            "Оператор"})]
    public class Обращение : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Primer.tСтатусОбращения fСтатус;
        
        private System.DateTime fДатаПоступления;
        
        private System.DateTime fДатаЗакрытия;
        
        private string fТелефон;
        
        private string fАдрес;
        
        private string fОбратившийся;
        
        private IIS.Primer.Обращение fДопОбращение;
        
        private IIS.Primer.Сотрудник fОтветственный;
        
        private IIS.Primer.ТипОбращения fТипОбращения;
        
        private IIS.Primer.Причина fПричина;
        
        private IIS.Primer.ВидОбращения fВидОбращения;
        
        private IIS.Primer.Сотрудник fОператор;
        
        //  *** Start programmer edit section *** (Обращение CustomMembers)

        //  *** End programmer edit section *** (Обращение CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Номер CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Номер Get start)

                //  *** End programmer edit section *** (Обращение.Номер Get start)
                int result = this.fНомер;
                //  *** Start programmer edit section *** (Обращение.Номер Get end)

                //  *** End programmer edit section *** (Обращение.Номер Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Номер Set start)

                //  *** End programmer edit section *** (Обращение.Номер Set start)
                this.fНомер = value;
                //  *** Start programmer edit section *** (Обращение.Номер Set end)

                //  *** End programmer edit section *** (Обращение.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Статус CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Статус CustomAttributes)
        public virtual IIS.Primer.tСтатусОбращения Статус
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Статус Get start)

                //  *** End programmer edit section *** (Обращение.Статус Get start)
                IIS.Primer.tСтатусОбращения result = this.fСтатус;
                //  *** Start programmer edit section *** (Обращение.Статус Get end)

                //  *** End programmer edit section *** (Обращение.Статус Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Статус Set start)

                //  *** End programmer edit section *** (Обращение.Статус Set start)
                this.fСтатус = value;
                //  *** Start programmer edit section *** (Обращение.Статус Set end)

                //  *** End programmer edit section *** (Обращение.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)

        //  *** End programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)
        public virtual System.DateTime ДатаПоступления
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.ДатаПоступления Get start)

                //  *** End programmer edit section *** (Обращение.ДатаПоступления Get start)
                System.DateTime result = this.fДатаПоступления;
                //  *** Start programmer edit section *** (Обращение.ДатаПоступления Get end)

                //  *** End programmer edit section *** (Обращение.ДатаПоступления Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.ДатаПоступления Set start)

                //  *** End programmer edit section *** (Обращение.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                //  *** Start programmer edit section *** (Обращение.ДатаПоступления Set end)

                //  *** End programmer edit section *** (Обращение.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗакрытия.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)

        //  *** End programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)
        public virtual System.DateTime ДатаЗакрытия
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get start)

                //  *** End programmer edit section *** (Обращение.ДатаЗакрытия Get start)
                System.DateTime result = this.fДатаЗакрытия;
                //  *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get end)

                //  *** End programmer edit section *** (Обращение.ДатаЗакрытия Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set start)

                //  *** End programmer edit section *** (Обращение.ДатаЗакрытия Set start)
                this.fДатаЗакрытия = value;
                //  *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set end)

                //  *** End programmer edit section *** (Обращение.ДатаЗакрытия Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Телефон CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Телефон Get start)

                //  *** End programmer edit section *** (Обращение.Телефон Get start)
                string result = this.fТелефон;
                //  *** Start programmer edit section *** (Обращение.Телефон Get end)

                //  *** End programmer edit section *** (Обращение.Телефон Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Телефон Set start)

                //  *** End programmer edit section *** (Обращение.Телефон Set start)
                this.fТелефон = value;
                //  *** Start programmer edit section *** (Обращение.Телефон Set end)

                //  *** End programmer edit section *** (Обращение.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Адрес Get start)

                //  *** End programmer edit section *** (Обращение.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Обращение.Адрес Get end)

                //  *** End programmer edit section *** (Обращение.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Адрес Set start)

                //  *** End programmer edit section *** (Обращение.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Обращение.Адрес Set end)

                //  *** End programmer edit section *** (Обращение.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Обратившийся.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Обратившийся CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Обратившийся CustomAttributes)
        [StrLen(255)]
        public virtual string Обратившийся
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Обратившийся Get start)

                //  *** End programmer edit section *** (Обращение.Обратившийся Get start)
                string result = this.fОбратившийся;
                //  *** Start programmer edit section *** (Обращение.Обратившийся Get end)

                //  *** End programmer edit section *** (Обращение.Обратившийся Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Обратившийся Set start)

                //  *** End programmer edit section *** (Обращение.Обратившийся Set start)
                this.fОбратившийся = value;
                //  *** Start programmer edit section *** (Обращение.Обратившийся Set end)

                //  *** End programmer edit section *** (Обращение.Обратившийся Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.ДопОбращение CustomAttributes)

        //  *** End programmer edit section *** (Обращение.ДопОбращение CustomAttributes)
        public virtual IIS.Primer.Обращение ДопОбращение
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.ДопОбращение Get start)

                //  *** End programmer edit section *** (Обращение.ДопОбращение Get start)
                IIS.Primer.Обращение result = this.fДопОбращение;
                //  *** Start programmer edit section *** (Обращение.ДопОбращение Get end)

                //  *** End programmer edit section *** (Обращение.ДопОбращение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.ДопОбращение Set start)

                //  *** End programmer edit section *** (Обращение.ДопОбращение Set start)
                this.fДопОбращение = value;
                //  *** Start programmer edit section *** (Обращение.ДопОбращение Set end)

                //  *** End programmer edit section *** (Обращение.ДопОбращение Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Ответственный CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Ответственный CustomAttributes)
        [NotNull()]
        public virtual IIS.Primer.Сотрудник Ответственный
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Ответственный Get start)

                //  *** End programmer edit section *** (Обращение.Ответственный Get start)
                IIS.Primer.Сотрудник result = this.fОтветственный;
                //  *** Start programmer edit section *** (Обращение.Ответственный Get end)

                //  *** End programmer edit section *** (Обращение.Ответственный Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Ответственный Set start)

                //  *** End programmer edit section *** (Обращение.Ответственный Set start)
                this.fОтветственный = value;
                //  *** Start programmer edit section *** (Обращение.Ответственный Set end)

                //  *** End programmer edit section *** (Обращение.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.ТипОбращения CustomAttributes)

        //  *** End programmer edit section *** (Обращение.ТипОбращения CustomAttributes)
        public virtual IIS.Primer.ТипОбращения ТипОбращения
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.ТипОбращения Get start)

                //  *** End programmer edit section *** (Обращение.ТипОбращения Get start)
                IIS.Primer.ТипОбращения result = this.fТипОбращения;
                //  *** Start programmer edit section *** (Обращение.ТипОбращения Get end)

                //  *** End programmer edit section *** (Обращение.ТипОбращения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.ТипОбращения Set start)

                //  *** End programmer edit section *** (Обращение.ТипОбращения Set start)
                this.fТипОбращения = value;
                //  *** Start programmer edit section *** (Обращение.ТипОбращения Set end)

                //  *** End programmer edit section *** (Обращение.ТипОбращения Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Причина CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Причина CustomAttributes)
        [NotNull()]
        public virtual IIS.Primer.Причина Причина
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Причина Get start)

                //  *** End programmer edit section *** (Обращение.Причина Get start)
                IIS.Primer.Причина result = this.fПричина;
                //  *** Start programmer edit section *** (Обращение.Причина Get end)

                //  *** End programmer edit section *** (Обращение.Причина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Причина Set start)

                //  *** End programmer edit section *** (Обращение.Причина Set start)
                this.fПричина = value;
                //  *** Start programmer edit section *** (Обращение.Причина Set end)

                //  *** End programmer edit section *** (Обращение.Причина Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.ВидОбращения CustomAttributes)

        //  *** End programmer edit section *** (Обращение.ВидОбращения CustomAttributes)
        public virtual IIS.Primer.ВидОбращения ВидОбращения
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.ВидОбращения Get start)

                //  *** End programmer edit section *** (Обращение.ВидОбращения Get start)
                IIS.Primer.ВидОбращения result = this.fВидОбращения;
                //  *** Start programmer edit section *** (Обращение.ВидОбращения Get end)

                //  *** End programmer edit section *** (Обращение.ВидОбращения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.ВидОбращения Set start)

                //  *** End programmer edit section *** (Обращение.ВидОбращения Set start)
                this.fВидОбращения = value;
                //  *** Start programmer edit section *** (Обращение.ВидОбращения Set end)

                //  *** End programmer edit section *** (Обращение.ВидОбращения Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        //  *** Start programmer edit section *** (Обращение.Оператор CustomAttributes)

        //  *** End programmer edit section *** (Обращение.Оператор CustomAttributes)
        [NotNull()]
        public virtual IIS.Primer.Сотрудник Оператор
        {
            get
            {
                //  *** Start programmer edit section *** (Обращение.Оператор Get start)

                //  *** End programmer edit section *** (Обращение.Оператор Get start)
                IIS.Primer.Сотрудник result = this.fОператор;
                //  *** Start programmer edit section *** (Обращение.Оператор Get end)

                //  *** End programmer edit section *** (Обращение.Оператор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Обращение.Оператор Set start)

                //  *** End programmer edit section *** (Обращение.Оператор Set start)
                this.fОператор = value;
                //  *** Start programmer edit section *** (Обращение.Оператор Set end)

                //  *** End programmer edit section *** (Обращение.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбращениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеE", typeof(IIS.Primer.Обращение));
                }
            }
            
            /// <summary>
            /// "ОбращениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеL", typeof(IIS.Primer.Обращение));
                }
            }
        }
    }
}
