//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primer
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Причина обращения.
    /// </summary>
    //  *** Start programmer edit section *** (Причина CustomAttributes)

    //  *** End programmer edit section *** (Причина CustomAttributes)
    [AutoAltered()]
    [Caption("Причина обращения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПричинаОбращенияE", new string[] {
            "Название as \'Название\'",
            "Код as \'Код\'"})]
    [View("ПричинаОбращенияL", new string[] {
            "Название as \'Название\'",
            "Код as \'Код\'"})]
    public class Причина : IIS.Primer.Справочник
    {
        
        private string fНазвание;
        
        private int fКод;
        
        //  *** Start programmer edit section *** (Причина CustomMembers)

        //  *** End programmer edit section *** (Причина CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Причина.Название CustomAttributes)

        //  *** End programmer edit section *** (Причина.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Причина.Название Get start)

                //  *** End programmer edit section *** (Причина.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Причина.Название Get end)

                //  *** End programmer edit section *** (Причина.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Причина.Название Set start)

                //  *** End programmer edit section *** (Причина.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Причина.Название Set end)

                //  *** End programmer edit section *** (Причина.Название Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        //  *** Start programmer edit section *** (Причина.Код CustomAttributes)

        //  *** End programmer edit section *** (Причина.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                //  *** Start programmer edit section *** (Причина.Код Get start)

                //  *** End programmer edit section *** (Причина.Код Get start)
                int result = this.fКод;
                //  *** Start programmer edit section *** (Причина.Код Get end)

                //  *** End programmer edit section *** (Причина.Код Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Причина.Код Set start)

                //  *** End programmer edit section *** (Причина.Код Set start)
                this.fКод = value;
                //  *** Start programmer edit section *** (Причина.Код Set end)

                //  *** End programmer edit section *** (Причина.Код Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПричинаОбращенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПричинаОбращенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПричинаОбращенияE", typeof(IIS.Primer.Причина));
                }
            }
            
            /// <summary>
            /// "ПричинаОбращенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПричинаОбращенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПричинаОбращенияL", typeof(IIS.Primer.Причина));
                }
            }
        }
    }
}
