//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primer
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справочник.
    /// </summary>
    //  *** Start programmer edit section *** (Справочник CustomAttributes)

    //  *** End programmer edit section *** (Справочник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправочникE", new string[] {
            "Актуально as \'Актуально\'"})]
    [View("СправочникL", new string[] {
            "Актуально as \'Актуально\'"})]
    public class Справочник : ICSSoft.STORMNET.DataObject
    {
        
        private bool fАктуально;
        
        //  *** Start programmer edit section *** (Справочник CustomMembers)

        //  *** End programmer edit section *** (Справочник CustomMembers)

        
        /// <summary>
        /// Актуально.
        /// </summary>
        //  *** Start programmer edit section *** (Справочник.Актуально CustomAttributes)

        //  *** End programmer edit section *** (Справочник.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                //  *** Start programmer edit section *** (Справочник.Актуально Get start)

                //  *** End programmer edit section *** (Справочник.Актуально Get start)
                bool result = this.fАктуально;
                //  *** Start programmer edit section *** (Справочник.Актуально Get end)

                //  *** End programmer edit section *** (Справочник.Актуально Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Справочник.Актуально Set start)

                //  *** End programmer edit section *** (Справочник.Актуально Set start)
                this.fАктуально = value;
                //  *** Start programmer edit section *** (Справочник.Актуально Set end)

                //  *** End programmer edit section *** (Справочник.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправочникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправочникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправочникE", typeof(IIS.Primer.Справочник));
                }
            }
            
            /// <summary>
            /// "СправочникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправочникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправочникL", typeof(IIS.Primer.Справочник));
                }
            }
        }
    }
}
